### ISSUE TITLE
[BUG] - Els comandaments funcionen a els MD

### ISSUE THREAD

**Issue by MrOrange9-JCT** [MrOrange9-JCT/Ezpezialet#3]
Els comandaments funcionen a els MD, i no hauríen.

**Comment by AleixFerre** [comment]
Pots comprovar si estàs a una guild fent
```
if message.guild:
 #Estic a una guild
else:
 #Estic a MD
```

**Comment by MrOrange9-JCT** [comment]
> Pots comprovar si estàs a una guild fent
> 
> ```
> if message.guild:
>  #Estic a una guild
> else:
>  #Estic a MD
> ```

Gràcies, però si vull que quan estigui a MD no es prossecin le comandes, haig de posar això a tots els comandaments?

**Comment by AleixFerre** [comment]
https://github.com/MrOrange9-JCT/Ezpezialet/blob/12275f2e3d12537e4f7764038da72f40adf87f78/codi/main.py#L57
Aquí ho fas prou bé però després de `await message.channel.send(random.choice(responses))`
Cal posar un `return` perque surti de la funció i no executi la resta del codi

**Comment by MrOrange9-JCT** [comment]
> https://github.com/MrOrange9-JCT/Ezpezialet/blob/12275f2e3d12537e4f7764038da72f40adf87f78/codi/main.py#L57
> 
> 
> Aquí ho fas prou bé però després de `await message.channel.send(random.choice(responses))`
> Cal posar un `return` perque surti de la funció i no executi la resta del codi

Doncs moltes gràcies! Ja funciona correctament.
